### PR TITLE
Implemented localDeleteNewline and fixed multi line delete

### LINKED ISSUE #7: PRIORITY: implement localDeleteNewline

### PR DESCRIPTION
**Pull request by shanthanu9**
Resolves #7

### CODE REVIEW

File: hello/assets/js/crdt.js [hunk 1]
```diff
@@ -306,6 +307,31 @@ class CRDT {
...
+        // console.log(`current line: ${this.data[lineNumber]}`)
+        var endIdentifier = endCharacter.identifiers[0];
+        var retCharacter = this.data[lineNumber][-1]; //Return character will be the last character in `lineNumber`
+        var lineToMerge = this.data.splice(lineNumber+1, 1)[0]; //Remove line `lineNumber+1`.
+        lineToMerge.shift(); //Remove 'starting' character from line to be merged
+        // console.log(`lineToMerge: ${lineToMerge}`);
+        //Merge `lineToMerge` to line `lineNumber` by offseting each character in `lineToMerge`
+        for(var character of lineToMerge) {
+            var modifiedCharacter = character;
+            modifiedCharacter.identifiers[0].position += endIdentifier.position;
```
Comment (rohit-mp) [inline hello/assets/js/crdt.js:331]: Shouldn't this be done for all `identifier` and not just `identifiers[0]` ?

Comment (rohit-mp) [reply hello/assets/js/crdt.js:331]: nvm got it
